import { latestWarehouseAddresses } from "./latestAddresses.mjs";

export const authUsers = {
  admin: { username: "admin", displayName: "管理员", role: "admin", password: "123456" },
  buyer: { username: "buyer", displayName: "Alex Chen", role: "buyer", password: "123456" },
  warehouse: { username: "warehouse", displayName: "仓库 Amy", role: "warehouse", password: "123456" },
  customer: { username: "customer", displayName: "客户 A", role: "customer", password: "123456" },
};

export const navItems = [
  { title: "首页总览", path: "/dashboard", roles: ["admin"] },
  {
    title: "采购任务",
    roles: ["admin"],
    children: [
      { title: "发布采购任务", path: "/purchase/tasks/new", roles: ["admin"] },
      { title: "采购任务列表", path: "/purchase/tasks", roles: ["admin"] },
      { title: "任务大厅", path: "/purchase/task-hall", roles: ["admin"] },
      { title: "接单记录", path: "/purchase/orders", roles: ["admin"] },
      { title: "超时提醒", path: "/purchase/timeout", roles: ["admin"] },
    ],
  },
  {
    title: "物流包裹",
    roles: ["admin"],
    children: [
      { title: "包裹列表", path: "/packages", roles: ["admin"] },
      { title: "在途包裹", path: "/packages/in-transit", roles: ["admin"] },
      { title: "预计到达提醒", path: "/packages/eta-alerts", roles: ["admin"] },
      { title: "包裹异常", path: "/packages/exceptions", roles: ["admin"] },
    ],
  },
  {
    title: "仓库收货",
    roles: ["admin", "warehouse"],
    children: [
      { title: "待确认包裹", path: "/warehouse/pending", roles: ["admin", "warehouse"] },
      { title: "已收货包裹", path: "/warehouse/received", roles: ["admin", "warehouse"] },
      { title: "超时待核查", path: "/warehouse/overdue", roles: ["admin", "warehouse"] },
      { title: "仓库操作费", path: "/warehouse/fees", roles: ["admin"] },
    ],
  },
  { title: "任务大厅", path: "/purchase/task-hall", roles: ["buyer"] },
  { title: "我的接单", path: "/purchase/orders", roles: ["buyer"] },
  { title: "买手采购回填", path: "/buyers/fill", roles: ["buyer"] },
  { title: "我的收款状态", path: "/buyers/payments", roles: ["buyer"] },
  {
    title: "客户资料",
    roles: ["customer"],
    children: [
      { title: "发布采购任务", path: "/customer/tasks/new", roles: ["customer"] },
      { title: "我的采购任务", path: "/customer/tasks", roles: ["customer"] },
      { title: "我的商品资料", path: "/customer/products", roles: ["customer"] },
      { title: "我的仓库地址", path: "/customer/warehouses", roles: ["customer"] },
    ],
  },
];

export const tasks = [
  {
    id: "PT-202607-001",
    requester: "管理员",
    source: "管理员发布",
    productName: "2024 Bowman Chrome Hobby Box",
    targetPrice: 1680,
    quantity: 80,
    accepted: 62,
    purchased: 44,
    arrived: 26,
    deadline: "2026-07-05T18:00:00",
    status: "接单中",
    overdue: false,
    buyer: "Alex Chen",
    requirement: "未拆封，盒角无明显撞痕，优先 eBay / Whatnot。",
    warehouse: "洛杉矶一号仓",
    recipient: "Amy Johnson",
  },
  {
    id: "PT-202607-002",
    requester: "客户 A",
    source: "客户发布",
    productName: "2023-24 Prizm Basketball Mega",
    targetPrice: 920,
    quantity: 120,
    accepted: 118,
    purchased: 96,
    arrived: 88,
    deadline: "2026-07-01T16:00:00",
    status: "超时",
    overdue: true,
    buyer: "Mia Wong",
    requirement: "目标单价内优先，超价必须备注平台截图。",
    warehouse: "纽约中转仓",
    recipient: "Ben Miller",
  },
  {
    id: "CT-202607-005",
    requester: "客户 A",
    source: "客户发布",
    productName: "2024 Topps Museum Baseball Case",
    targetPrice: 7600,
    quantity: 12,
    accepted: 4,
    purchased: 0,
    arrived: 0,
    deadline: "2026-07-15T18:00:00",
    status: "已发布",
    overdue: false,
    buyer: "未分配",
    requirement: "客户指定 case 采购，要求外箱完整，买手需上传平台成交截图。",
    warehouse: "纽约中转仓",
    recipient: "Ben Miller",
  },
];

export const fillRecords = [
  {
    id: "BF-240701-018",
    orderId: "ORD-8801",
    buyer: "Alex Chen",
    productName: "2024 Bowman Chrome Hobby Box",
    quantity: 16,
    unitPrice: 1658,
    settlement: 27960,
    overPrice: false,
    trackingNo: "1Z999AA10123456784",
    recipient: "Amy Johnson",
    warehouse: "洛杉矶一号仓",
    warehouseEta: "2026-07-03T18:00:00",
    auditStatus: "待审核",
    payStatus: "待付款",
  },
  {
    id: "BF-240701-019",
    orderId: "ORD-8802",
    buyer: "Mia Wong",
    productName: "2023-24 Prizm Basketball Mega",
    quantity: 24,
    unitPrice: 945,
    settlement: 23980,
    overPrice: true,
    trackingNo: "9611020987654312345672",
    recipient: "Ben Miller",
    warehouse: "纽约中转仓",
    warehouseEta: "2026-07-01T14:00:00",
    auditStatus: "已审核",
    payStatus: "已付待确认",
  },
];

export const packages = [
  {
    id: "PKG-0701-001",
    carrier: "UPS",
    trackingNo: "1Z999AA10123456784",
    buyer: "Alex Chen",
    product: "Bowman Chrome Hobby x 16",
    expectedAt: "2026-07-03T18:00:00",
    status: "在途",
    warehouse: "洛杉矶一号仓",
    recipient: "Amy Johnson",
    productQty: 16,
    linkedPurchases: 1,
    paidAmount: 27960,
    paidPendingConfirmAmount: 27960,
    inboundCost: 0,
    exceptionAmount: 0,
    paymentStatus: "paid_pending_confirm",
    overdue: false,
  },
  {
    id: "PKG-0701-002",
    carrier: "USPS",
    trackingNo: "9611020987654312345672",
    buyer: "Mia Wong",
    product: "Prizm Basketball Mega x 24",
    expectedAt: "2026-07-01T14:00:00",
    status: "预计到达超时",
    warehouse: "纽约中转仓",
    recipient: "Ben Miller",
    productQty: 24,
    linkedPurchases: 1,
    paidAmount: 23980,
    paidPendingConfirmAmount: 23980,
    inboundCost: 0,
    exceptionAmount: 0,
    paymentStatus: "paid_pending_confirm",
    overdue: true,
  },
  {
    id: "PKG-0701-003",
    carrier: "FedEx",
    trackingNo: "794612345678",
    buyer: "Chris Lee",
    product: "Topps Chrome Sapphire x 10",
    expectedAt: "2026-07-02T11:00:00",
    receivedAt: "2026-07-02T13:22:00",
    status: "已收货",
    warehouse: "洛杉矶一号仓",
    recipient: "Amy Johnson",
    productQty: 10,
    linkedPurchases: 1,
    paidAmount: 13320,
    paidPendingConfirmAmount: 0,
    inboundCost: 13320,
    exceptionAmount: 0,
    paymentStatus: "confirmed_received",
    overdue: false,
  },
  {
    id: "PKG-0701-004",
    carrier: "UPS",
    trackingNo: "1Z222BB99887766554",
    buyer: "Noah Smith",
    product: "Select NFL Blaster x 40",
    expectedAt: "2026-06-29T10:00:00",
    status: "物流异常",
    warehouse: "俄勒冈免税仓",
    recipient: "Chris Davis",
    productQty: 40,
    linkedPurchases: 2,
    paidAmount: 22400,
    paidPendingConfirmAmount: 16800,
    inboundCost: 0,
    exceptionAmount: 5600,
    paymentStatus: "paid_pending_confirm",
    overdue: true,
  },
];

export const packageExceptions = [
  {
    id: "EXP-202607-001",
    packageId: "PKG-0701-004",
    carrier: "UPS",
    trackingNo: "1Z222BB99887766554",
    buyer: "Noah Smith",
    product: "Select NFL Blaster x 40",
    reason: "物流异常，官网显示递送失败，仓库未收到实物。",
    owner: "买手 Noah / UPS",
    amount: 5600,
    resolution: "next_credit",
    status: "processing",
    evidence: "官网截图、买手平台订单截图",
    note: "异常金额暂不进入实际入库成本，处理完成后进入下次抵扣。",
    createdAt: "2026-07-01T18:40:00",
  },
  {
    id: "EXP-202606-014",
    packageId: "PKG-0630-012",
    carrier: "USPS",
    trackingNo: "9400111206213999999999",
    buyer: "Mia Wong",
    product: "Prizm Basketball Mega x 6",
    reason: "少货 2 盒，仓库照片与买手回填数量不一致。",
    owner: "买手 Mia",
    amount: 1880,
    resolution: "refund",
    status: "resolved",
    evidence: "开箱照片、入库清点单",
    note: "已退款，不参与本月正常入库成本。",
    createdAt: "2026-06-28T12:10:00",
  },
];

export const productProfiles = [
  {
    id: "SKU-BC-2024-HOBBY",
    name: "2024 Bowman Chrome Hobby Box",
    category: "棒球卡盒",
    brand: "Topps",
    spec: "未拆封 Hobby Box，盒角无明显撞痕",
    owner: "管理员",
    referencePrice: 1680,
    status: "启用",
    updatedAt: "2026-07-02",
  },
  {
    id: "SKU-PRIZM-2324-MEGA",
    name: "2023-24 Prizm Basketball Mega",
    category: "篮球卡盒",
    brand: "Panini",
    spec: "Mega Box，允许轻微外膜磨损",
    owner: "客户 A",
    referencePrice: 920,
    status: "待审核",
    updatedAt: "2026-07-01",
  },
];

export const warehouseAddresses = [
  ...latestWarehouseAddresses,
  {
    id: "WH-LAX-01",
    name: "洛杉矶一号仓",
    owner: "管理员",
    contactName: "Amy Johnson",
    phone: "+1 626 555 0188",
    addressLine1: "17888 Railroad St",
    addressLine2: "Suite 208",
    city: "City of Industry",
    state: "CA",
    zipCode: "91748",
    country: "US",
    status: "启用",
  },
  {
    id: "WH-NY-TRANSIT",
    name: "纽约中转仓",
    owner: "客户 A",
    contactName: "Ben Miller",
    phone: "+1 718 555 0126",
    addressLine1: "41-20 39th St",
    city: "Long Island City",
    state: "NY",
    zipCode: "11104",
    country: "US",
    status: "待审核",
  },
];

export const reconciliationRecords = [
  {
    id: "REC-202607-A",
    period: "2026-07",
    paidPendingConfirmAmount: 67740,
    inboundCost: 13320,
    exceptionAmount: 5600,
    status: "待确认",
  },
  {
    id: "REC-202606-A",
    period: "2026-06",
    paidPendingConfirmAmount: 0,
    inboundCost: 186000,
    exceptionAmount: 1880,
    status: "已完成",
  },
];
